In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

### Imports

In [3]:
import sys
import json
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

### Define global variables

In [4]:
method_name_dict = {
    "ape": "APE",
    "low_perplexity_prompts": "Low Perplexity",
    "chat_gpt_prompts": "Ad hoc",
    "generic_instruction": "Generic Instruction",
    "manual": "PromptSource",
    "no_instruction": "Null Instruction",
    "rlprompt": "RLPrompt"
}

dataset_name_dict = {
    "ag_news": "AG News",
    "anli": "ANLI",
    "boolq": "BoolQ",
    "imdb": "IMDB",
    "tweet_emotion": "Emotion",
    "cosmos_qa": "CosmosQA",
    "hellaswag": "HellaSwag",
    "nq_open": "NQ-Open",
    "trivia_qa": "TriviaQA"
}

model_family_dict = {
    "bloom": "BLOOM",
    "gptneo": "GPT Neo",
    "llama": "LLaMA",
    "opt": "OPT"
}

task_type_dict = {
    "CLS": ["ag_news", "anli", "boolq", "imdb", "tweet_emotion"],
    "MCQ": ["hellaswag", "cosmos_qa"],
    "GQA": ["trivia_qa", "nq_open"]
}

all_tasks = task_type_dict["CLS"] + task_type_dict["MCQ"] + task_type_dict["GQA"]

### Define useful functions

In [5]:
def build_raw_df_from_results(results_dir):
    # define relevant keys
    metadata_keys = ["model", "dataset", "instruction"]  # , 'method']
    metric_keys = [
        "few_shot_accuracy",
        "zero_shot_accuracy",
        "unperturbed_accuracy",
        "perturbed_accuracy",
        "perturbation_drop_in_accuracy",
        "selectional_sensitivity",
        "permutational_sensitivity",
    ]

    results = []
    # populate results by iterating over log files in results_dir
    for filename in tqdm(os.listdir(results_dir)):
        raw_dict = json.loads(open(os.path.join(results_dir, filename), "r").read())
        new_dict = dict()

        # populate metadata fields
        for k in metadata_keys:
            new_dict[k] = raw_dict["metadata"][k]
        new_dict["method"] = raw_dict["metadata"]["instructions_dir"].split("/")[1]

        # populate metric fields
        for k in metric_keys:
            if k in raw_dict["results"]:
                new_dict[k] = raw_dict["results"][k]

        # append to results
        results.append(new_dict)

    # create raw_results_df
    raw_results_df = pd.DataFrame.from_records(results)

    # function to make sure all NaNs are np.nan
    enforce_np_nan = lambda x: x.apply(
        lambda y: next((i for i in y if not pd.isna(i)), np.nan)
    )

    # group by metadata keys and enforce np.nan
    raw_results_df = (
        raw_results_df.groupby(metadata_keys)
        .apply(enforce_np_nan)
        .reset_index(drop=True)
    )

    return raw_results_df


def compute_relative_gains(input_df, column_name):
    def compute_relative_gain_within_group(group, column_name):
        task_name = group.name[1]
        mean = group[column_name].mean()
        group[f"normalized_{column_name}"] = 100 * (group[column_name] - mean) / mean
        return group

    return input_df.groupby(["model", "dataset"], group_keys=False).apply(
        compute_relative_gain_within_group, column_name=column_name
    )


def compute_unnormalized_scores(input_df, column_name):
    def multiply100(group, column_name):
        group[f"normalized_{column_name}"] = 100 * (group[column_name])
        return group

    return input_df.groupby(["model", "dataset"], group_keys=False).apply(
        multiply100, column_name=column_name
    )


def average_across_models_and_seeds(df_normalized, column_name):
    # for each dataset and method, compute mean score across models and seeds
    results_df = df_normalized.pivot_table(index='method', columns='dataset', values=f"normalized_{column_name}", aggfunc='mean')
    # rename index and columns if necessary
    results_df = results_df[all_tasks].rename(index=method_name_dict, columns=dataset_name_dict).reset_index()

    return results_df

def create_style_df(results_df, higher_is_better):
    # prepare results_df for display
    order = [
        "Null Instruction", "Generic Instruction",
        "PromptSource", "Ad hoc",
        "Low Perplexity", "APE", "RLPrompt"
    ]
    results_df["method"] = pd.Categorical(results_df["method"], categories=order, ordered=True)
    results_df = results_df.sort_values("method")
    results_df = results_df.set_index("method")
    
    df_s = results_df.style.format("{:.3f}")
    df_s = df_s.apply(
        lambda x: ["font-weight: bold" if val == (x.max() if higher_is_better else x.min()) else "" for val in x]
    )

    return df_s


def get_aggregated_df(
    input_df, column_name, higher_is_better=True, use_relative_gain=True
):
    normalized_df = compute_relative_gains(input_df, column_name) if use_relative_gain else \
                    compute_unnormalized_scores(input_df, column_name)
    results_df = average_across_models_and_seeds(normalized_df, column_name)
    results_df_s = create_style_df(results_df, higher_is_better)

    return results_df_s

def collate_by_task_type(results_df, ascending=True):
    if not isinstance(results_df, pd.DataFrame):
        results_df = results_df.data
    collated_df = pd.DataFrame()
    for task_type, task_list in task_type_dict.items():
        collated_df[task_type] = results_df[
            [dataset_name_dict[task] for task in task_list]
        ].mean(axis=1)

    df_s = collated_df.style.format("{:.3f}")
    if ascending:
        df_s = df_s.apply(
            lambda x: ["font-weight: bold" if val == x.max() else "" for val in x]
        )

    return df_s

### Create all raw dataframes

In [6]:
RESULTS_DIR = "../results/"
raw_df = build_raw_df_from_results(RESULTS_DIR)

# Trick to give No Instruction a weight of 5 for fair comparison with remaining instructions
condition = raw_df['method'] == "no_instruction"
selected_rows = raw_df.loc[condition]
duplicated_rows = pd.concat([selected_rows]*4, ignore_index=True)
raw_df = pd.concat([raw_df, duplicated_rows], ignore_index=True)

#print(raw_df.groupby(['model', 'dataset', 'method']).size().to_string())

# create dataframes for ablations
models = raw_df.model.unique()
small_models = [model for model in models if not ("6b" in model or "7b" in model or "13b" in model or "20b" in model)]
big_models = [model for model in models if ("6b" in model or "7b" in model or "13b" in model or "20b" in model)]

df_big = raw_df[raw_df.model.isin(big_models)].reset_index(drop=True)
df_small = raw_df[raw_df.model.isin(small_models)].reset_index(drop=True)

def df_family(family):
    return raw_df.loc[raw_df["model"].str.startswith(family, na=False)].reset_index(drop=True)

100%|██████████| 17475/17475 [00:04<00:00, 4084.99it/s]

# Display aggregated results
## Main results
### Accuracy metrics (Table 5)

In [7]:
get_aggregated_df(raw_df, "zero_shot_accuracy", use_relative_gain=True, higher_is_better=True)

In [8]:
get_aggregated_df(raw_df, "few_shot_accuracy", use_relative_gain=True, higher_is_better=True)

In [9]:
get_aggregated_df(raw_df, "perturbed_accuracy", use_relative_gain=True, higher_is_better=True)

### Sensitivity metrics (Table 6)

In [10]:
get_aggregated_df(raw_df, 'selectional_sensitivity', use_relative_gain=False, higher_is_better=False)

In [11]:
get_aggregated_df(raw_df, 'permutational_sensitivity', use_relative_gain=False, higher_is_better=False)

## Display model scale ablation results
### Small models (Table 8)

In [12]:
collate_by_task_type(get_aggregated_df(df_small, 'zero_shot_accuracy', use_relative_gain=True, higher_is_better=True))

In [13]:
collate_by_task_type(get_aggregated_df(df_small, 'few_shot_accuracy', use_relative_gain=True, higher_is_better=True))

### Big models (Table 8)

In [14]:
collate_by_task_type(get_aggregated_df(df_big, "zero_shot_accuracy", use_relative_gain=True, higher_is_better=True))

In [15]:
collate_by_task_type(get_aggregated_df(df_big, "few_shot_accuracy", use_relative_gain=True, higher_is_better=True))

## Display model family ablation results (Table 7)
### BLOOM

In [16]:
get_aggregated_df(df_family("bloom"), "zero_shot_accuracy", use_relative_gain=True)

In [17]:
get_aggregated_df(df_family("bloom"), "few_shot_accuracy", use_relative_gain=True)

### GPTNeo

In [18]:
get_aggregated_df(df_family("gptneo"), "zero_shot_accuracy", use_relative_gain=True)

In [19]:
get_aggregated_df(df_family("gptneo"), "few_shot_accuracy", use_relative_gain=True)

### LLaMA

In [20]:
get_aggregated_df(df_family("llama"), "zero_shot_accuracy", use_relative_gain=True)

In [21]:
get_aggregated_df(df_family("llama"), "few_shot_accuracy", use_relative_gain=True)

### OPT

In [22]:
get_aggregated_df(df_family("opt"), "zero_shot_accuracy", use_relative_gain=True)

In [23]:
get_aggregated_df(df_family("opt"), "few_shot_accuracy", use_relative_gain=True)